apiVersion: connectors.aiops.ibm.com/v1beta1
kind: BundleManifest
metadata:
  name: github-grpc-connector-template
spec:
  prereqs:
    repo: 'https://github.com/cookcm/cp4aiops-connectors-github-template'
    branch: main
    authSecret:
      name: test-utilities-github-token
    components:
      - name: deployment
        path: /bundle-artifacts/prereqs
        type: kustomize
  instanced:
    repo: 'https://github.com/cookcm/cp4aiops-connectors-github-template'
    branch: main
    authSecret:
      name: test-utilities-github-token
    components:
      - name: connector
        path: /bundle-artifacts/connector
        type: kustomize
