apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml

configurations:
  - namereference.yaml
  - varreference.yaml

images:
  - name: github-grpc-connector-template
    newName: docker.io/cookcm/sample-github-template
    newTag: latest

vars:
  - name: SERVICE_NAME
    objref:
      kind: Service
      name: github-grpc-connector-template
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: SERVICE_NAMESPACE
    objref:
      kind: Service
      name: github-grpc-connector-template
      apiVersion: v1
    fieldref:
      fieldpath: metadata.namespace
